### PR TITLE
Create ai-learn-allowed-coins.user.js

### PR DESCRIPTION
**Pull request by 0SkillAllLuck**
Simpler version of the Bulk Train option that uses the currently allowed coins

### CODE REVIEW

**Comment by coffeeneer** [comment]
Ah, this basically combines the coinlist export and bulk training in one go. I'm thinking it would be nice to merge this with the other script since it shares 90% of the functionality. So from a maintainability aspect that would probably be best.

**Comment by RoiTainMent** [comment]
awesome addition to the script set, works great. I would definitely prefer not to have this merged with the other script though, just merged into the main branch so people can access it. I know personally I use the export for other things beyond just my training, I track a lot of my coin additions/changes so exporting a mass list and just searching for changes makes my life way easier.

**Comment by coffeeneer** [comment]
Yeah @RoiTainMent I wouldn't get rid of the export, just add this as a second way to start the bulk training. As the whole bulk training part is exactly the same. This would then use the coin list instead of the input popup for the coin pairs, or maybe prefill it so you can make changes before starting.

**Comment by 0SkillAllLuck** [comment]
@coffeeneer Maybe this script is not required, I could modify the bulk training script to include the currently allowed coins as the default value. Maybe that is the better option?

**Comment by coffeeneer** [comment]
@0SkillAllLuck That would be great. I think the script is most commonly used to train the list people have selected in their hopper config. So always having this list as the default value would be benificial I think, you can still easily select everything in the list and overwrite it.

**Pull request closed without merging**
